/**
*/

-- tabla usuarios

DROP TABLE IF EXISTS EA_USUARIO;
CREATE TABLE IF NOT EXISTS EA_USUARIO
(
     EA_ID          INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL 
    ,EA_USUARIO     VARCHAR(50) NOT NULL
    ,EA_CLAVE       VARCHAR(50) NOT NULL
);

-- claves encriptadas con el algoritmo MD5

INSERT INTO EA_USUARIO  (EA_USUARIO, EA_CLAVE)
            VALUES      ('profe','81dc9bdb52d04dc20036dbd8313ed055');

INSERT INTO EA_USUARIO  (EA_USUARIO, EA_CLAVE)
            VALUES      ('emilio.armas@epn.edu.ec','dad0edde3552d170218b5239818a9da6');     

-- tabla coordenadas

DROP TABLE IF EXISTS EA_COORDENADA;
CREATE TABLE IF NOT EXISTS EA_COORDENADA
(
     EA_ID                  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL 
    ,EA_CAPACIDAD_BELICA    INTEGER NOT NULL
    ,EA_GEOLOCALIZACION     VARCHAR(50) NOT NULL
    ,EA_TIPO_ARSENAL        VARCHAR(50) NOT NULL
    ,EA_FECHA_INGRESO       VARCHAR(50) DEFAULT(datetime('now'))
);

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (6,'GPS6','act');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (8,'GPS8','abbccdt');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (9,'GPS9','aaabbcd');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (5,'GPS5','bct');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (1,'GPS1','bc');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (3,'GPS3','bcd');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (0,'GPS0','ab');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (5,'GPS5','bct');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (7,'GPS7','aaabbct');

INSERT INTO EA_COORDENADA   (EA_CAPACIDAD_BELICA, EA_GEOLOCALIZACION, EA_TIPO_ARSENAL)
            VALUES          (1,'GPS1','bc');

SELECT * FROM EA_USUARIO;

SELECT * FROM EA_COORDENADA;